name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # roda todo dia à meia-noite (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Generate snake
      uses: Platane/snk@v3
      with:
        github_user_name: anaKyn-hub
        outputs: ./dist/github-contribution-grid-snake.svg

    - name: Push to output branch
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Add snake animation" || echo "No changes to commit"
        git push origin HEAD:output --force
